### PR TITLE
Implement frame-to-frame video navigation

### PR DESCRIPTION
**Pull request by ToukL**
- Uses a hack to navigate frame-to-frame in video, based on [requestVideoFrameCallback](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestVideoFrameCallback) and [https://github.com/angrycoding/requestVideoFrameCallback-prev-next](https://github.com/angrycoding/requestVideoFrameCallback-prev-next)

WARNING: this works only in Chrome (not in Firefox). Not tested in other navigators.

- Adds a 'Jump step' setting to directly jump a certain amount of seconds backward and forward

Changes video navigation buttons:

- step-backward and step-forward are used to go to previous and next frames in video
- add double-backward and double-forward buttons for Jump step setting
- add chevron-left and chevron-right to go to previous/next video of volume

### CODE REVIEW

**Comment by mzur** [comment]
This is an interesting approach! I need to test this thoroughly with different videos because I had so much trouble with this in the past. There are also a couple of things that could be streamlined for the final implementation but I'll get to that once I tested it a bit.

However, this also implements the "jump forward/backward by a fixed number of seconds", right (https://github.com/biigle/core/issues/262)? Could you please split this from the "jump frame-by-frame" changes and send both in separate PRs? The jumping by seconds can be merged much sooner then.

**Comment by mzur** [comment]
For the record: I mentioned the workaround in the [W3C discussion](https://github.com/w3c/media-and-entertainment/issues/4) I follow and others say that it might not produce perfect results in all cases. [This article](https://web.dev/articles/requestvideoframecallback-rvfc) recommends the [WebCodecs API](https://developer.mozilla.org/docs/Web/API/WebCodecs_API) for frame-accurate applications. [I had a look at this](https://github.com/biigle/core/issues/433#issuecomment-1482788582), too, but as the linked StackOverflow answer mentions, it only works if the media is demuxed. And I think there is no easy solution for that if we still allow many different video file formats in BIIGLE.

**Comment by ToukL** [comment]
> This is an interesting approach! I need to test this thoroughly with different videos because I had so much trouble with this in the past. There are also a couple of things that could be streamlined for the final implementation but I'll get to that once I tested it a bit.
> 
> However, this also implements the "jump forward/backward by a fixed number of seconds", right (#262)? Could you please split this from the "jump frame-by-frame" changes and send both in separate PRs? The jumping by seconds can be merged much sooner then.

**Comment by ToukL** [comment]
I did split the PR in two.

I know it's just a workaround that needs more testing and cleaning, if you have time and ideas for that it would be great ! I implemented it like that because we need the frame-by-frame navigation, even if not perfect fro now. I'm open to any suggestion though !

**Comment by mzur** [comment]
Thanks! We'll continue in the new PRs.

**Pull request closed without merging**
