### PR TITLE
Improve navbar (for mobile)

### PR DESCRIPTION
**Pull request by mzur**
So I was fed up with the navbar behavior on mobile for the final time. While we won't optimize all of BIIGLE for mobile anytime soon, at least the navbar should work. Here are the changes:

| before | after |
| --- | ---|
| desktop view:  | |
| Screenshot from 2023-10-23 16-30-33 | Screenshot from 2023-10-23 16-30-38 |
| Screenshot from 2023-10-23 16-44-16 | Screenshot from 2023-10-23 16-43-19 |
| mobile view:  | |
| Screen Shot 2023-10-23 at 16 31 06 | Screen Shot 2023-10-23 at 16 31 04 |
| Screen Shot 2023-10-23 at 16 31 13 | Screen Shot 2023-10-23 at 16 31 10 |

@dlangenk Comments?

### CODE REVIEW

**Comment by dlangenk** [comment]
> @dlangenk Comments?

Really like that this is working right now. I have to say from a visual standpoint I liked the old design better without the outlines arround the objects, less button looking buttons, but I guess it's still worth it to have everything working without that much hassle.

**Comment by mzur** [comment]
> Really like that this is working right now. 

You mean you like the current behavior of the navbar (i.e. it gets larger on mobile and possibly hides content like in the annotation tool)?

> I have to say from a visual standpoint I liked the old design better without the outlines arround the objects [...]

I stole that idea from GitHub again :smiley: But if you have a strong opinion against it maybe we have to ask more people what they think. I've now updated the background color of the buttons so they are less "intruding":

image

**Comment by dlangenk** [comment]
> > Really like that this is working right now.
> 
> You mean you like the current behavior of the navbar (i.e. it gets larger on mobile and possibly hides content like in the annotation tool)?

Nope I mean the new layout.

> 
> > I have to say from a visual standpoint I liked the old design better without the outlines arround the objects [...]
> 
> I stole that idea from GitHub again 😃 But if you have a strong opinion against it maybe we have to ask more people what they think. I've now updated the background color of the buttons so they are less "intruding":
> 
> image

Yes, I like that better. Can keep it that way I'd say.

**Comment by mzur** [comment]
Alright, thanks!

**Pull request merged**
