### PR TITLE
Upgrade OpenLayers to v9

### LINKED ISSUE #250: Upgrade OpenLayers
Upgrade OpenLayers to version 6 as it offers better support for touch and pen input devices (openlayers/openlayers#9244). This is a major version bump and might be complicated to integrate with our existing modifications to OpenLayers.

### PR DESCRIPTION
**Pull request by mzur**
This is an attempt to upgrade OpenLayers from v5 to the current v9. It may offer better performance and new features.

Plan:

- [x] Migrate the canvas source from `@biigle/ol` to core
- [x] Migrate the polygon brush from `@biigle/ol` to core
- [x] Upgrade to OpenLayers v6. Check for relevant new features. Resolves #250 
   - [x] Continue [release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0) at "Layers can only be added to a single map".
   - [x] Walk through remaining v6 release notes.
- [x] Upgrade to OpenLayers v7. Check for relevant new features.
   - [x] Read [release notes](https://github.com/openlayers/openlayers/releases/tag/v7.0.0).
   - [x] Walk through remaining v7 release notes.
- [x] Upgrade to OpenLayers v8. Check for relevant new features.
   - [x] Read [release notes](https://github.com/openlayers/openlayers/releases/tag/v8.0.0).
   - [x] Walk through remaining v8 release notes.
- [x] Upgrade to OpenLayers v9. Check for relevant new features.
   - [x] Read [release notes](https://github.com/openlayers/openlayers/releases/tag/v9.0.0).
   - [x] Walk through remaining v9 release notes.
- [x] Enable the Rectangle and Ellipse geometry types again (either in core or in a `@biigle/ol` that is based on v9). 
   - https://github.com/openlayers/openlayers/compare/main...biigle:openlayers:v9-biigle
- [x] Do extensive manual QA and comparison to v5 of all features (including shortcuts).
- [x] Release `@biigle/ol:v9.2.4`.
- [x] Upgrade use of `@biigle/ol` in:
   - [x] biigle/magic-sam https://github.com/biigle/magic-sam/pull/26
   - [x] biigle/reports https://github.com/biigle/reports/pull/124
   - [x] biigle/geo https://github.com/biigle/geo/pull/55
   - [x] biigle/laserpoints https://github.com/biigle/laserpoints/pull/80
   - [x] biigle/maia https://github.com/biigle/maia/pull/174

Known issues:
- [x] Capturing a screenshot does not produce a high-DPI image. Fix?
- [x] Drawing and modifying with a polygon brush is slower. Maybe newer/slower turfjs? Fix?
- [x] Selecting a complicated (magic wand) annotation is extremely slow. Fix?
   - Is the `selectedAnnotations` watcher necessary or does it double the work?
   - Maybe remove select interaction as described in https://github.com/openlayers/openlayers/pull/9961?
   - Use `Layer#getFeatures(pixel)` introduced in v6.1?
- [x] ~~Zooming and panning of images is sometimes (?) more janky. Fix?~~
   - The map object was accidentally made reactive through the minimap, which made everything slow.
- [x] ~~Static image display is flickering sometimes during zoom/pan. Fix?~~
   - It's only the image/canvas layer that's flickering. The annotation layer remains visible!
   - No idea. Only observed this sometimes in Firefox when the dev console is open. Never in Chrome.
- [x] Video playback is faster with an updated implementation (that works with the minimap)!
- [x] Seems to fix https://github.com/biigle/core/issues/626.
- [x] Zoom (to extent) buttons are smaller. Fix?
- [x] Update magic wand snapshot only when tool is active and using `throttle()`.
- [x] Update video minimap more efficiently with `source.change()` instead of `layer.change()` so no render listener is required any more.
- [x] Tiled image minimap sometimes flickers.
- [x] Zoom to full image no longer has a padding. Fix?
- [x] Selecting multiple overlapping annotations seems different. Fix?
- [x] ~~The video annotation tool shows a strange artifact at the bottom of the video.~~
   - Seems to be a Firefox thing. The video element is fine but once the video is drawn onto a canvas, the artifacts are there.
- [x] Look for possible bottlenecks (e.g. event listeners) in image/video drawing.
   - Double render through drawn video frame and then refreshed annotations?
   - Is the `selectedAnnotations` watcher necessary or does it double the work?

### CODE REVIEW

**Comment by mzur** [comment]
@dlangenk @lehecht Could you please check out this branch and try to break the image/video annotation tools when you have time? After checking out the branch you have to run `npm install` and `npm run dev` once. This PR upgrades the most important third-party library in BIIGLE four major versions and I don't want to publish it before adequate eyeballing.

**Comment by dlangenk** [comment]
I found a bug, which wasn't there before (at least I can reproduce it at biigle.de) [Should we post them here?]
1. Activate the brush tool and draw an annotation.
2. Deactivate it and click on the newly created annotation
3. Activate the modify brush (T) and paint a new annotation to the top left of the current one, without intersection.
4. The previous annotation is now gone and the new one is there.

**Comment by dlangenk** [comment]
I also get a warning in the console: No map visible because the map container's width or height are 0.

**Comment by dlangenk** [comment]
That is everything I found. So great work🎉

**Comment by mzur** [comment]
@dlangenk Thanks, this should be fixed now. It also fixed #873.

@lehecht Anything to add?

**Pull request merged**
